substitutions:
  api_encryption_key: "" # REQUIRED!
  ota_password: "" # REQUIRED!
  git_ref: "" # REQUIRED!

  crop_dig1: &crop_dig1
    top_left:
      x: 0
      y: 0
    bottom_right:
      x: 0
      y: 0

  crop_dig2:
    <<: *crop_dig1

  crop_dig3:
    <<: *crop_dig1

  crop_dig4:
    <<: *crop_dig1

  crop_dig5:
    <<: *crop_dig1

  crop_dig6:
    <<: *crop_dig1

  name: "aquasense"
  friendly_name: "Aquasense"
  language: "en"
  i18n:
    aquasense:
      de: !include i18n/de.yaml
      en: !include i18n/en.yaml

packages:
  base: !include
    file: ../../packages/base.yaml
  e32s3cam: !include
    file: ../../packages/esp32_s3_cam.yaml

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: "siku2.aquasense"
    version: "0.1.0"

dashboard_import:
  package_import_url: "github://siku2/esphome-projects/projects/aquasense/core.yaml@main"
  import_full_config: false

external_components:
  - source:
      type: git
      url: "https://github.com/siku2/esphome-projects"
      ref: "${git_ref}"
      path: "components"
    components: ["camera_snapshot", "tflite"]

api:
  encryption:
    key: "${api_encryption_key}"

ota:
  - platform: "esphome"
    password: "${ota_password}"

camera_snapshot:
  update_interval: "10s"
  rotate: "90°"
  before_snapshot:
    - light.turn_on: "e32s3cam_flash"
    - delay: "100ms"
  after_snapshot:
    - light.turn_off: "e32s3cam_flash"

tflite:
  op_resolver:
    builtin:
      - "add"
      - "conv_2d"
      - "dequantize"
      - "fully_connected"
      - "leaky_relu"
      - "max_pool_2d"
      - "mul"
      - "quantize"
      - "reshape"
      - "softmax"
  allocator:
    size: "150 kB"
  model:
    - id: "digits_model"
      file: "https://github.com/jomjol/AI-on-the-edge-device/raw/refs/heads/main/sd-card/config/dig-cont_0900_s3_q.tflite"
    - id: "analog_model"
      file: "https://github.com/jomjol/AI-on-the-edge-device/raw/refs/heads/main/sd-card/config/ana-cont_1500_s2_q.tflite"
  interpreter:
    - id: "digits_interpreter"
      model: "digits_model"
    - id: "analog_interpreter"
      model: "analog_model"

sensor:
  - &dig1
    id: "dig1"
    name: "${i18n.aquasense.${language}.dig1}"
    accuracy_decimals: 0
    filters:
      - lambda: !lambda |
          return std::floorf(x);
    entity_category: "diagnostic"
    platform: "tflite"
    interpreter: "digits_interpreter"
    crop: "${crop_dig1}"

  - <<: *dig1
    id: "dig2"
    name: "${i18n.aquasense.${language}.dig2}"
    crop: "${crop_dig2}"

  - <<: *dig1
    id: "dig3"
    name: "${i18n.aquasense.${language}.dig3}"
    crop: "${crop_dig3}"

  - <<: *dig1
    id: "dig4"
    name: "${i18n.aquasense.${language}.dig4}"
    crop: "${crop_dig4}"

  - <<: *dig1
    id: "dig5"
    name: "${i18n.aquasense.${language}.dig5}"
    crop: "${crop_dig5}"

  - <<: *dig1
    id: "dig6"
    name: "${i18n.aquasense.${language}.dig6}"
    crop: "${crop_dig6}"

  - id: "combined"
    name: "${i18n.aquasense.${language}.combined}"
    unit_of_measurement: "m³"
    device_class: "water"
    state_class: "total_increasing"
    accuracy_decimals: 1
    platform: "template"
    lambda: !lambda |
      float sum = 0.0f;
      sum += id(dig1).state * 10000.0f;
      sum += id(dig2).state * 1000.0f;
      sum += id(dig3).state * 100.0f;
      sum += id(dig4).state * 10.0f;
      sum += id(dig5).state * 1.0f;
      sum += id(dig6).state * 0.1f;
      return sum;
    update_interval: "never"
