substitutions:
  api_encryption_key: "" # REQUIRED!
  ota_password: "" # REQUIRED!
  git_ref: "" # REQUIRED!

  name: "aquasense"
  friendly_name: "Aquasense"
  language: "en"
  i18n:
    aquasense:
      de: !include i18n/de.yaml
      en: !include i18n/en.yaml

packages:
  base: !include ../../packages/base.yaml
  e32s3cam: !include ../../packages/esp32_s3_cam.yaml
  #
  dig: !include ./digits.yaml
  aqcsmp: !include ./meter_consumption.yaml
  aqss: !include ./snapshot.yaml

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: "siku2.aquasense"
    version: "0.1.0"

dashboard_import:
  package_import_url: "github://siku2/esphome-projects/projects/aquasense/core.yaml@main"
  import_full_config: false

external_components:
  - source:
      type: git
      url: "https://github.com/siku2/esphome-projects"
      ref: "${git_ref}"
      path: "components"
    components: ["camera_snapshot", "tflite"]

api:
  encryption:
    key: "${api_encryption_key}"

ota:
  - platform: "esphome"
    password: "${ota_password}"
