substitutions:
  api_encryption_key: "" # REQUIRED!
  ota_password: "" # REQUIRED!
  git_ref: "" # REQUIRED!
  blind_left_cover_id: "" # REQUIRED!
  blind_right_cover_id: "" # REQUIRED!

  name: "esp-catimor"
  friendly_name: "Catimor"
  language: "en"
  i18n:
    catimor:
      de: !include translations/de.yaml
      en: !include translations/en.yaml

packages:
  base: !include
    file: ../../packages/base.yaml
  m5stack_cores3_lite: !include
    file: ../../packages/m5stack_cores3_lite.yaml

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: "siku2.esp-catimor"
    version: "0.1.0"

dashboard_import:
  package_import_url: "github://siku2/esphome-projects/projects/catimor/core.yaml@main"
  import_full_config: false

external_components:
- source:
    type: git
    url: "https://github.com/siku2/esphome-projects"
    ref: "${git_ref}"
    path: "components"
  components: [ "m5stack_4encodermotor" ]

api:
  encryption:
    key: "${api_encryption_key}"

ota:
- platform: "esphome"
  password: "${ota_password}"

m5stack_4encodermotor:
- id: "motor_encoder"
  update_interval: "100ms"
  current:
    id: "m54em_current"
    name: "${i18n.catimor[language].m54em_current}"
    filters:
    - sliding_window_moving_average:
        window_size: 10
        send_every: 10
        send_first_at: 10
    - round: 3
    - delta: "10%"
  voltage:
    id: "m54em_voltage"
    name: "${i18n.catimor[language].m54em_voltage}"
    filters:
    - delta: 0.1

cover:
- &cover_north
  id: "cover_north"
  name: "${i18n.catimor[language].cover_north}"
  device_class: "shutter"
  platform: "m5stack_4encodermotor"
  m5stack_4encodermotor_id: "motor_encoder"
  motor: "M3"
  min_current: "0.1A"
  soft_start_stop: true
  open_duration: "29s"
  close_duration: "28.5s"
  acceleration_wait_time: "0.5s"

- <<: *cover_north
  id: "cover_south"
  name: "${i18n.catimor[language].cover_south}"
  motor: "M4"

number:
- id: "display_timeout"
  name: "${i18n.catimor[language].display_timeout}"
  unit_of_measurement: "s"
  entity_category: "CONFIG"
  mode: "box"
  platform: "template"
  optimistic: true
  initial_value: 10
  restore_value: true
  min_value: 5
  max_value: 180
  step: 5

sensor:
- &blind_left_position
  id: "blind_left_position"
  on_value:
  - script.execute: "script_sync_sliders"
  platform: "homeassistant"
  entity_id: "${blind_left_cover_id}"
  attribute: "current_position"

- <<: *blind_left_position
  id: "blind_right_position"
  entity_id: "${blind_right_cover_id}"

- &blind_left_tilt
  <<: *blind_left_position
  id: "blind_left_tilt"
  on_value:
  - script.execute: "script_sync_sliders"
  attribute: "current_tilt_position"

- <<: *blind_left_tilt
  id: "blind_right_tilt"
  entity_id: "${blind_right_cover_id}"

script:
- !include scripts/set_cover_position.yaml
- !include scripts/set_cover_tilt.yaml
- !include scripts/sync_sliders.yaml

touchscreen:
- id: !extend m5s3l_touchscreen
  on_release:
  - if:
      condition: lvgl.is_paused
      then:
      - logger.log: "LVGL resuming"
      - lvgl.resume:
      - lvgl.widget.redraw:
      - light.turn_on: "m5s3l_lcd_backlight"

lvgl:
  displays: [ "m5s3l_lcd" ]
  touchscreens:
  - touchscreen_id: "m5s3l_touchscreen"
  theme:
    dark_mode: true
    button:
      text_color: "0xCDD6F4"
      radius: 4
      border_width: 1
      border_color: "0x585B70"
      pressed:
        bg_color: "0x313244"
      checked:
        bg_color: "0x89B4FA"
        border_color: "0x89B4FA"
        text_color: "0x1E1E2E"
    slider:
      radius: 4
      indicator:
        bg_color: "0x89B4FA"
        radius: 4
      knob:
        radius: 4
        pad_top: -14
        pad_bottom: -14
        bg_color: "0x89B4FA"
        border_color: "0x1E1E2E"
        border_width: 1
    label:
      text_color: "0xCDD6F4"
  on_idle:
    timeout: !lambda >
      return (id(display_timeout).state * 1000);
    then:
    - logger.log: "LVGL is idle"
    - light.turn_off: "m5s3l_lcd_backlight"
    - lvgl.pause:
  pages:
  - !include pages/blinds_control.yaml
