spi:
  miso_pin: "GPIO18"
  clk_pin: "GPIO19"

sensor:
- &probe_west_temperature
  id: "probe_west_temperature"
  name: "${i18n.grilldisplay[language].probe_west}"
  unit_of_measurement: "°C"
  device_class: "temperature"
  state_class: "measurement"
  accuracy_decimals: 0
  filters:
  - round: 1
  - filter_out: "NaN"
  - timeout: "5s"
  - delta: 0.5
  # Re-emit the last value every 5s even if it hasn't changed
  - timeout:
      timeout: "5s"
      value: "last"
  platform: "max31855"
  update_interval: "500ms"
  cs_pin: "GPIO20"

- <<: *probe_west_temperature
  id: "probe_east_temperature"
  name: "${i18n.grilldisplay[language].probe_east}"
  cs_pin: "GPIO38"

- <<: *probe_west_temperature
  id: "probe_meat_temperature"
  name: "${i18n.grilldisplay[language].probe_grey}"
  cs_pin: "GPIO21"
