# AXP2101 Power Management IC
#
# See: <https://github.com/protoconcept/axp2101>
# See: <https://www.lcsc.com/datasheet/C3036461.pdf>
#
# ## Variables
#
# - `address`: I2C address of the motor driver. Default is `0x34`.
#
# ## Namespace
#
# `axp2101`
#
# ## Components
#
# ### Binary Sensor
#
# - `axp2101_current_limit_state`: Current limit state indicator.
# - `axp2101_vbus_good_indication`: VBUS bad indicator.
#
# ### I2C Device
#
# - `axp2101_i2cdev`: The I2C device.
#
# ### Output
#
# - `axp2101_dldo1`: DLDO1 power output control.

defaults:
  address: 0x34

i2c_device:
- id: "axp2101_i2cdev"
  address: "${address}"

output:
- id: "axp2101_dldo1"
  platform: "template"
  type: "float"
  write_action:
  - logger.log:
      tag: "axp2101"
      format: "Setting DLDO1 to %f"
      args: [ 'state' ]
  - script.execute:
      id: "axp2101_set_ldo"
      index: 7
      turn_on: !lambda 'return state != 0.0;'
      step: !lambda 'return (int)(state * 28.5);'

script:
- id: "axp2101_set_ldo"
  mode: "queued"
  parameters:
    # aldo1, aldo2, aldo3, aldo4, bld01, bldo2, cpusldo, dldo1, dldo2
    index: "int"
    turn_on: "bool"
    step: "int" # Depends on the LDO, -1 to ignore
  then:
  - lambda: !lambda |
      if (index > 8) {
        ESP_LOGE("axp2101", "Invalid LDO index: %d", index);
        return;
      }

      uint8_t control_bit = index % 8;
      uint8_t control_addr = 0x90 + (index / 8);
      uint8_t voltage_addr = 0x92 + index;

      uint8_t value;
      auto err = id(axp2101_i2cdev)->read_register(control_addr, &value, sizeof value);
      if (err != ERROR_OK) {
        ESP_LOGE("axp2101", "Failed to read control register %d", control_addr);
        return;
      }
      if (turn_on) {
        value |= (1 << control_bit);
      } else {
        value &= ~(1 << control_bit);
      }
      err = id(axp2101_i2cdev)->write_register(control_addr, &value, sizeof value);
      if (err != ERROR_OK) {
        ESP_LOGE("axp2101", "Failed to write control register %d", control_addr);
        return;
      }

      if (step == -1) return;

      value = step;
      err = id(axp2101_i2cdev)->write_register(voltage_addr, &value, sizeof value);
      if (err != ERROR_OK) {
        ESP_LOGE("axp2101", "Failed to write voltage register %d", voltage_addr);
        return;
      }

- id: "axp2101_read_pmu_status1"
  mode: "restart"
  then:
  - lambda: !lambda |
      uint8_t addr = 0x00; // PMU status1
      uint8_t value;
      auto err = id(axp2101_i2cdev)->read_register(addr, &value, sizeof value);
      if (err != ERROR_OK) {
        ESP_LOGE("axp2101", "Failed to read PMU status 1");
        return;
      }
      // Bit 0: Current Limit State (1 = in current limit)
      id(axp2101_current_limit_state)->publish_state((value & 0x01) != 0);
      // Bit 5: VBUS good indication (1 = good)
      id(axp2101_vbus_good_indication)->publish_state((value & 0x20) == 0);

binary_sensor:
- &axp2101_current_limit_state
  id: "axp2101_current_limit_state"
  name: "Current Limit State"
  device_class: "problem"
  entity_category: "diagnostic"
  platform: "template"

- <<: *axp2101_current_limit_state
  id: "axp2101_vbus_good_indication"
  name: "VBUS Good Indication"

interval:
- interval: "30s"
  then:
  - script.execute: "axp2101_read_pmu_status1"
