# M5Stack 4 Encoder Motor Driver
#
# See: <https://docs.m5stack.com/en/module/Module_4EncoderMotor_V1.1>
#
# ## Variables
#
# - `address`: I2C address of the motor driver. Default is `0x24`.
#
# ## Namespace
#
# `m54em`
#
# ## Components
#
# ### I2C Device
#
# - `m54em_i2cdev`: The I2C device.
#
# ### Number
#
# - `m54em_motor1_speed`: Motor 1 speed control.
# - `m54em_motor2_speed`: Motor 2 speed control.
# - `m54em_motor3_speed`: Motor 3 speed control.
# - `m54em_motor4_speed`: Motor 4 speed control.
#
# ### Script
#
# - `m54em_init`: Initialize all 4 motors. (Uses `m54em_set_mode` and `m54em_set_soft_start_stop`)
# - `m54em_set_mode`: Set mode of a motor.
# - `m54em_set_soft_start_stop`: Enable/disable soft start/stop for each motor.
# - `m54em_set_speed`: Set speed of a motor.
#
# ### Sensor
#
# - `m54em_fw_version`: Firmware version.
# - `m54em_bl_version`: Bootloader version.
# - `m54em_current`: Current consumption.
# - `m54em_voltage`: Supply voltage.

defaults:
  address: 0x24

i2c_device:
- id: "m54em_i2cdev"
  address: "${address}"

sensor:
- &m54em_fw_version
  id: "m54em_fw_version"
  name: "Encoder firmware version"
  state_class: ""
  accuracy_decimals: 0
  entity_category: "DIAGNOSTIC"
  platform: "template"
  update_interval: "30s" # This is more like a retry. Once we have a value we stop updating ourselves.
  lambda: !lambda |
    uint8_t value;
    auto err = id(m54em_i2cdev)->read_register(0xFE, &value, sizeof value);
    if (err != ERROR_OK) return {};
    // Once we have a first value we can stop updating ourselves
    id(m54em_fw_version)->stop_poller();
    return value;

- <<: *m54em_fw_version
  id: "m54em_bl_version"
  name: "Encoder bootloader version"
  lambda: !lambda |
    uint8_t value;
    auto err = id(m54em_i2cdev)->read_register(0xFC, &value, sizeof value);
    if (err != ERROR_OK) return {};
    // Once we have a first value we can stop updating ourselves
    id(m54em_bl_version)->stop_poller();
    return value;

- &m54em_current
  id: "m54em_current"
  name: "Encoder current"
  unit_of_measurement: "A"
  device_class: "current"
  accuracy_decimals: 3
  state_class: "MEASUREMENT"
  filters:
  - sliding_window_moving_average:
      window_size: 10
      send_every: 10
      send_first_at: 10
  - delta: "10%"
  platform: "template"
  update_interval: "50ms" # We end up emitting a new value every 500 ms.
  lambda: !lambda |
    float value;
    auto err = id(m54em_i2cdev)->read_register(0x90, (uint8_t *)&value, sizeof value);
    if (err != ERROR_OK) return {};
    return value;

- <<: *m54em_current
  id: "m54em_voltage"
  name: "Encoder voltage"
  unit_of_measurement: "V"
  device_class: "voltage"
  accuracy_decimals: 3
  filters:
  - delta: 0.1 # 100 mV
  update_interval: "1s"
  lambda: !lambda |
    uint8_t data[2];
    auto err = id(m54em_i2cdev)->read_register(0xB0, data, sizeof data);
    if (err != ERROR_OK) return {};
    // From protocol PDF: ((ADC Value 12bits-L) + (ADC Value 12bits-H)*256)/255*3.3/0.16
    uint16_t raw = data[0] | (data[1] << 8);
    return raw / 4095.0 * 3.3 / 0.16;

script:
- id: "m54em_init"
  mode: "queued"
  parameters:
    motor1_mode: "int" # 0 - 3 (NORMAL, POSITION LOCK, SPEED LOCK)
    motor1_soft_start: "bool"
    motor2_mode: "int" # 0 - 3 (NORMAL, POSITION LOCK, SPEED LOCK)
    motor2_soft_start: "bool"
    motor3_mode: "int" # 0 - 3 (NORMAL, POSITION LOCK, SPEED LOCK)
    motor3_soft_start: "bool"
    motor4_mode: "int" # 0 - 3 (NORMAL, POSITION LOCK, SPEED LOCK)
    motor4_soft_start: "bool"
  then:
  - script.execute:
      id: "m54em_set_mode"
      index: 0
      mode: !lambda 'return motor1_mode;'
  - script.execute:
      id: "m54em_set_mode"
      index: 1
      mode: !lambda 'return motor2_mode;'
  - script.execute:
      id: "m54em_set_mode"
      index: 2
      mode: !lambda 'return motor3_mode;'
  - script.execute:
      id: "m54em_set_mode"
      index: 3
      mode: !lambda 'return motor4_mode;'
  - script.execute:
      id: "m54em_set_soft_start_stop"
      motor1: !lambda 'return motor1_soft_start;'
      motor2: !lambda 'return motor2_soft_start;'
      motor3: !lambda 'return motor3_soft_start;'
      motor4: !lambda 'return motor4_soft_start;'

- id: "m54em_set_mode"
  mode: "queued"
  parameters:
    # 0 - 3
    index: "int"
    # 0 - 3 (NORMAL, POSITION LOCK, SPEED LOCK)
    mode: "int"
  then:
  - lambda: !lambda |
      uint8_t addr = 0x50 + (index * 0x10);
      uint8_t value = mode;
      auto err = id(m54em_i2cdev)->write_register(addr, &value, sizeof value);
      if (err == ERROR_OK) ESP_LOGI("m54em", "Set motor %d mode to %d", index, mode);
      else                 ESP_LOGE("m54em", "Failed to set motor %d mode to %d", index, mode);

- id: "m54em_set_soft_start_stop"
  mode: "queued"
  parameters:
    motor1: "bool"
    motor2: "bool"
    motor3: "bool"
    motor4: "bool"
  then:
  - lambda: !lambda |
      uint8_t addr = 0xD1;
      uint8_t value = 0x00;
      if (motor1) value |= 0x1;
      if (motor2) value |= 0x2;
      if (motor3) value |= 0x4;
      if (motor4) value |= 0x8;
      auto err = id(m54em_i2cdev)->write_register(addr, &value, sizeof value);
      if (err == ERROR_OK) ESP_LOGI("m54em", "Set soft start-stop to %x", value);
      else                 ESP_LOGE("m54em", "Failed to set soft start-stop to %x", value);

- id: "m54em_set_speed"
  mode: "queued"
  parameters:
    # 0 - 3
    index: "int"
    # -127 - 127
    duty: "int"
  then:
  - lambda: !lambda |
      esphome::number::Number *speed_component;
      switch (index) {
        case 0:
          speed_component = id(m54em_motor1_speed);
          break;
        case 1:
          speed_component = id(m54em_motor2_speed);
          break;
        case 2:
          speed_component = id(m54em_motor3_speed);
          break;
        case 3:
          speed_component = id(m54em_motor4_speed);
          break;
        default:
          ESP_LOGE("m54em", "Invalid motor index %d", index);
          return;
      }

      uint8_t addr = 0x20 + index;
      uint8_t value = duty;
      auto err = id(m54em_i2cdev)->write_register(addr, &value, sizeof value);
      if (err != ERROR_OK) {
        ESP_LOGE("m54em", "Failed to set motor %d speed to %d", index, duty);
        return;
      }
      ESP_LOGI("m54em", "Set motor %d speed to %d", index, duty);
      speed_component->publish_state(duty);

number:
- &m54em_motor1_speed
  id: "m54em_motor1_speed"
  name: "Motor 1 speed"
  platform: "template"
  min_value: -127.0
  max_value: 127.0
  step: 1.0
  set_action:
    then:
    - script.execute:
        id: "m54em_set_speed"
        index: 0
        duty: !lambda 'return x;'
  optimistic: false
  restore_value: false
  initial_value: 0.0

- <<: *m54em_motor1_speed
  id: "m54em_motor2_speed"
  name: "Motor 2 speed"
  set_action:
    then:
    - script.execute:
        id: "m54em_set_speed"
        index: 1
        duty: !lambda 'return x;'

- <<: *m54em_motor1_speed
  id: "m54em_motor3_speed"
  name: "Motor 3 speed"
  set_action:
    then:
    - script.execute:
        id: "m54em_set_speed"
        index: 2
        duty: !lambda 'return x;'

- <<: *m54em_motor1_speed
  id: "m54em_motor4_speed"
  name: "Motor 4 speed"
  set_action:
    then:
    - script.execute:
        id: "m54em_set_speed"
        index: 3
        duty: !lambda 'return x;'
