# M5Stack Cores3 Lite
#
# See: <https://docs.m5stack.com/en/core/CoreS3-Lite>
#
# ## Variables
#
# ## Namespace
#
# `m5s3l`
#
# ## Components
#
# ### Display
#
# - `m5s3l_lcd`: The built-in LCD display.
#
# ### Switch
#
# - `m5s3l_lcd_backlight`: The LCD backlight control.

packages:
  axp2101: !include axp2101.yaml

external_components:
- source: "../components"
  components: [ "aw9523" ]

esp32:
  board: "esp32-s3-devkitc-1"
  flash_size: "16MB"
  cpu_frequency: "240MHz"
  framework:
    type: "esp-idf"

psram:
  mode: "octal"
  speed: "80MHz"

aw9523:
  id: "m5s3l_aw9523"
  latch_inputs: true
  p0_push_pull: true

i2c:
  sda: "GPIO12"
  scl: "GPIO11"
  scan: false
  frequency: "100kHz"

spi:
  clk_pin: "GPIO36"
  interface: "hardware"
  mosi_pin: "GPIO37"
  miso_pin:
    number: "GPIO35"
    allow_other_uses: true

binary_sensor:
- &m5s3l_es_int
  id: "m5s3l_es_int"
  name: "AW9523: ES Interrupt"
  entity_category: "DIAGNOSTIC"
  platform: "gpio"
  pin:
    aw9523: "m5s3l_aw9523"
    number: 3
    inverted: true # External pull-up

- <<: *m5s3l_es_int
  id: "m5s3l_tf_sw"
  name: "MicroSD Detected"
  pin:
    aw9523: "m5s3l_aw9523"
    number: 4
    inverted: true # External pull-up

- <<: *m5s3l_es_int
  id: "m5s3l_lcd_touch_int"
  name: "LCD Touch Interrupt"
  pin:
    aw9523: "m5s3l_aw9523"
    number: 10
    inverted: true # External pull-up
    # Forward the interrupt to GPIO21 so the touch screen works.
    forward_interrupt: true

- <<: *m5s3l_es_int
  id: "m5s3l_aw_int"
  name: "AW9523: AW Interrupt"
  pin:
    aw9523: "m5s3l_aw9523"
    number: 11
    inverted: true # External pull-up

# TODO: does this even exist? It's not in the schematic.
# sensor:
# - id: "m5s3l_proximity"
#   platform: "ltr_als_ps"
#   address: 0x23
#   type: "ALS_PS"
#   auto_mode: true
#   gain: "1x"
#   integration_time: "100ms"
#   ps_cooldown: "5s"
#   update_interval: "60s"
#   ambient_light: "Ambient Light"

number:
- id: "m5s3l_lcd_backlight"
  name: "LCD Backlight"
  entity_category: "CONFIG"
  unit_of_measurement: "%"
  platform: "template"
  min_value: 0.0
  max_value: 100.0
  step: 5.0
  set_action:
  # actual responsive range 0.6 -> 1.0
  - output.set_level:
      id: "axp2101_dldo1"
      level: !lambda |
        if (x == 0.0) return 0.0;
        float min = 0.6;
        float max = 1.0;
        return (x / 100.0) * (max - min) + min;
  update_interval: "never"
  optimistic: true
  restore_value: false
  initial_value: 0.0

i2s_audio:
- id: "m5s3l_i2s_audio"
  i2s_lrclk_pin: "GPIO33"
  i2s_bclk_pin: "GPIO34"

speaker:
- id: "m5s3l_speaker"
  platform: "i2s_audio"
  dac_type: "external"
  i2s_dout_pin: "GPIO14"
  i2s_audio_id: "m5s3l_i2s_audio"

display:
- id: "m5s3l_lcd"
  update_interval: "never"
  auto_clear_enabled: false
  platform: "mipi_spi"
  model: "ILI9341"
  dc_pin:
    number: "GPIO35"
    allow_other_uses: true
  reset_pin:
    aw9523: "m5s3l_aw9523"
    number: 9
  cs_pin:
    number: "GPIO3"
    ignore_strapping_warning: true
  dimensions: "320x240"
  invert_colors: true
  transform:
    swap_xy: false
    mirror_x: true
    mirror_y: true

touchscreen:
- id: "m5s3l_touchscreen"
  display: "m5s3l_lcd"
  transform:
    mirror_x: true
    mirror_y: true
    swap_xy: false
  update_interval: never
  platform: "ft63x6"
  reset_pin:
    aw9523: "m5s3l_aw9523"
    number: 0
  interrupt_pin:
    number: "GPIO21"
    mode: "INPUT_PULLUP"
