# See: <https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions>

name: Pages
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases
        sudo apt-get update
        sudo apt-get install -y kicad pipx xvfb
        pipx install --system-site-packages InteractiveHtmlBom

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - uses: astral-sh/setup-uv@v6

    - name: Build interactive HTML BOM
      run: ./x.py

    - uses: actions/upload-pages-artifact@v3
      with:
        path: public

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
