# See: <https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions>

name: Pages
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add kicad repo
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases

    - name: Install apt packages
      uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40 # v1
      with:
        packages: kicad pipx xvfb

    - name: Install pipx packages
      run: |
        pipx install --system-site-packages interactivehtmlbom

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

    - name: Build interactive HTML BOM
      run: ./x.py

    - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
      with:
        path: public

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
